# Generated by Django 6.0.2 on 2026-02-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок статьи (до 200 символов)', max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Введите содержание статьи', verbose_name='Содержание')),
                ('author', models.CharField(help_text='Имя автора статьи', max_length=100, verbose_name='Автор')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('slug', models.SlugField(help_text='Уникальный URL-идентификатор статьи', max_length=200, unique=True, verbose_name='URL-адрес')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'blog_posts',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['title'], name='blog_posts_title_4401ee_idx'), models.Index(fields=['author'], name='blog_posts_author_846702_idx')],
            },
        ),
    ]
